const fs=require('fs'),vm=require('vm');const dir=process.argv[2]||'/mnt/data/grade7-staar-rla-comprehensive';const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(dir+'/content.js','utf8'),c);const D=c.window.STAAR7_DATA;let errors=[],warnings=[];
const skills=D.skills,qmap=new Map(D.questions.map(q=>[q.id,q])),emap=new Map(D.ecrPrompts.map(e=>[e.id,e])),pids=new Set(D.passages.map(p=>p.id));
const duplicate=(a)=>new Set(a).size!==a.length;
for(const q of D.questions){if(!skills[q.skill])errors.push(`Unknown skill ${q.skill} on ${q.id}`);const correct=Array.isArray(q.correct)?q.correct:[q.correct],expected=q.type==='multi'?2:3;if(!Array.isArray(q.distractors)||q.distractors.length!==expected)errors.push(`Bad distractors ${q.id}`);if(correct.some(x=>q.distractors.includes(x))||duplicate([...correct,...q.distractors]))errors.push(`Duplicate choices ${q.id}`);if(!q.explanation)errors.push(`No explanation ${q.id}`);for(const p of q.passageIds||[])if(!pids.has(p))errors.push(`Unknown passage ${p} on ${q.id}`);}
for(const e of D.ecrPrompts){if(!skills[e.skill]||skills[e.skill].mode!=='ecr')errors.push(`Bad ECR skill ${e.id}`);for(const p of e.passageIds||[])if(!pids.has(p))errors.push(`Unknown ECR passage ${p}`);}
for(const [id,s] of Object.entries(skills)){const n=D.questions.filter(q=>q.skill===id).length,m=D.ecrPrompts.filter(e=>e.skill===id).length;if(s.mode==='objective'&&n<24)errors.push(`${id} only ${n} objective questions`);if(s.mode==='ecr'&&m<4)errors.push(`${id} only ${m} prompts`);}
let allTested=new Set();const formSummary=[];
for(const f of D.forms){let points=0,read=0,write=0,multi=0,ecr=0;if(f.itemIds.length!==45)errors.push(`${f.id} length ${f.itemIds.length}`);for(const id of f.itemIds){if(emap.has(id)){points+=10;ecr++;allTested.add(emap.get(id).skill);continue;}const q=qmap.get(id);if(!q){errors.push(`${f.id} missing ${id}`);continue;}points+=q.points;if(q.type==='multi')multi++;if(q.skill.startsWith('r-'))read++;else write++;if(!skills[q.skill].tested)errors.push(`${f.id} includes non-tested ${q.skill}`);allTested.add(q.skill);}if(points!==56)errors.push(`${f.id} points ${points}`);if(read<26||read>28)errors.push(`${f.id} reading ${read}`);if(write<17||write>19)errors.push(`${f.id} writing ${write}`);if(multi!==2)errors.push(`${f.id} multi ${multi}`);if(ecr!==1)errors.push(`${f.id} ecr ${ecr}`);formSummary.push({form:f.id,items:f.itemIds.length,points,reading:read,writing:write,multi,ecr});}
const tested=Object.entries(skills).filter(([,s])=>s.tested).map(([id])=>id),absent=tested.filter(x=>!allTested.has(x));if(absent.length)errors.push(`Tested skills absent from fixed forms: ${absent.join(', ')}`);
if(D.days.length<90)errors.push(`Only ${D.days.length} daily activities`);for(let i=0;i<D.days.length;i++){if(D.days[i].day!==i+1)errors.push(`Day sequence breaks at ${i+1}`);if('week' in D.days[i])errors.push(`Day ${i+1} still has week grouping`);}
function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}function rngFrom(seed){let a=hashString(String(seed));return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}function shuffled(arr,rng){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}function select(pool,count,rng){const sp=shuffled(pool,rng),chosen=[],per={};for(const item of sp){const key=(item.passageIds&&item.passageIds[0])||'standalone';if((per[key]||0)>=2&&chosen.length<Math.min(count,pool.length-2))continue;chosen.push(item);per[key]=(per[key]||0)+1;if(chosen.length===count)break;}if(chosen.length<count)for(const item of sp)if(!chosen.includes(item)){chosen.push(item);if(chosen.length===count)break;}return chosen;}
for(const [id,s] of Object.entries(skills)){if(s.mode!=='objective')continue;const pool=D.questions.filter(q=>q.skill===id),sets=[];for(let v=1;v<=4;v++){const a=select(pool,8,rngFrom(`${id}-version-${v}`)).map(q=>q.id);if(a.length!==8||duplicate(a))errors.push(`${id} quiz ${v} invalid`);sets.push(a.sort().join('|'));}if(new Set(sets).size<4)warnings.push(`${id} fixed quizzes are not all distinct`);}
const result={errors,warnings,counts:{skills:Object.keys(skills).length,testedObjective:Object.values(skills).filter(s=>s.tested&&s.mode==='objective').length,testedWritingLabs:Object.values(skills).filter(s=>s.tested&&s.mode==='ecr').length,nonTested:Object.values(skills).filter(s=>!s.tested).length,questions:D.questions.length,ecr:D.ecrPrompts.length,forms:D.forms.length,days:D.days.length,fixedFormSkillCoverage:allTested.size},formSummary};console.log(JSON.stringify(result,null,2));fs.writeFileSync(dir+'/VALIDATION.json',JSON.stringify(result,null,2));if(errors.length)process.exit(1);
