(function(){
"use strict";
const D=window.StatisticsPracticeData;
const main=document.getElementById('main');
const dlg=document.getElementById('leave-dialog');
const STORAGE='statisticsPracticeResults.v1';
const state={view:'home',examId:null,quiz:null,result:null,filter:'all'};

function hashString(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function rng(seed){return mulberry32(hashString(seed));}
function shuffle(arr,r){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function loadResults(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]');}catch{return[];}}
function saveResults(a){localStorage.setItem(STORAGE,JSON.stringify(a.slice(0,150)));}
function record(r){const a=loadResults();a.unshift({id:r.id,examId:r.examId,skillId:r.skillId,mode:r.mode,label:r.label,score:r.correct,total:r.total,percent:r.percent,completedAt:r.completedAt,skillStats:r.skillStats||[]});saveResults(a);}
function masteryMap(){const agg={};for(const id of Object.keys(D.skills))agg[id]={correct:0,total:0,attempts:0};for(const r of loadResults()){for(const s of r.skillStats||[]){if(!agg[s.id])continue;agg[s.id].correct+=Number(s.correct)||0;agg[s.id].total+=Number(s.total)||0;agg[s.id].attempts++;}}for(const x of Object.values(agg))x.percent=x.total?Math.round(100*x.correct/x.total):null;return agg;}
function masteryBadge(x){if(!x||x.percent==null)return `<span class="mastery-badge unseen">Not attempted</span>`;const cls=x.percent<60?'weak':x.percent<80?'developing':'strong';const label=x.percent<60?'Needs attention':x.percent<80?'Developing':'Strong';return `<span class="mastery-badge ${cls}">${label} • ${x.percent}%</span>`;}
function cumulativeWeaknesses(m){return Object.entries(m).filter(([,x])=>x.percent!=null).sort((a,b)=>a[1].percent-b[1].percent||D.skills[a[0]].label.localeCompare(D.skills[b[0]].label));}
let mathQueue=Promise.resolve();
function typeset(){const mj=window.MathJax;if(!mj)return;const ready=mj.startup&&mj.startup.promise?mj.startup.promise:Promise.resolve();mathQueue=mathQueue.then(()=>ready).then(()=>mj.typesetPromise?mj.typesetPromise([main]):undefined).catch(e=>console.warn(e));}
function go(view,p={}){if(state.quiz&&!state.result&&view!=='quiz'){confirmLeave(()=>reallyGo(view,p));return;}reallyGo(view,p);}
function reallyGo(view,p={}){state.view=view;state.examId=p.examId??state.examId;if(view!=='quiz')state.quiz=null;if(view!=='results')state.result=null;window.scrollTo(0,0);render();}
function confirmLeave(cb){if(dlg&&dlg.showModal){dlg.showModal();const h=()=>{dlg.removeEventListener('close',h);if(dlg.returnValue==='confirm')cb();};dlg.addEventListener('close',h);}else if(confirm('Leave this quiz? Your current answers will be lost.'))cb();}
function render(){if(state.view==='home')home();else if(state.view==='exam')examPage(state.examId);else if(state.view==='quiz')quizPage();else if(state.view==='results')resultsPage();else if(state.view==='progress')progressPage();else aboutPage();main.focus({preventScroll:true});typeset();}

function home(){const cards=Object.values(D.exams).map(e=>`<article class="exam-card"><span class="exam-number">Exam ${esc(e.number)}</span><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="chips"><span class="chip">4 fixed forms + Random</span><span class="chip">${e.skills.length} focused skills</span></div><button class="primary-button" data-action="open-exam" data-exam="${e.id}">Open exam & skills</button></article>`).join('');const a=loadResults(),m=masteryMap(),attempted=Object.values(m).filter(x=>x.percent!=null).length,priority=cumulativeWeaknesses(m).filter(([,x])=>x.percent<60).length;
main.innerHTML=`<section class="hero"><div><p class="eyebrow">Statistics course practice</p><h1>Find the weak spots. Practice the exact skill. Check improvement.</h1><p>Use a diagnostic exam to identify weaknesses, then work focused skill quizzes. Every submitted question includes the correct answer and an explanation.</p><div class="hero-note">✓ Four reproducible diagnostic forms, three fixed skill versions, and random practice</div></div></section><section class="content-wrap"><div class="section-heading"><h2>Diagnostic exams</h2><p>The sequence follows the class review quizzes.</p></div><div class="exam-grid">${cards}</div><section class="panel progress-snapshot"><div class="section-heading"><div><h2>Progress and weaknesses</h2><p>Cumulative results from completed activities on this browser.</p></div><button class="secondary-button" data-action="progress">View progress</button></div><div class="progress-summary-grid"><div><strong>${a.length}</strong><span>activities completed</span></div><div><strong>${attempted}/${Object.keys(D.skills).length}</strong><span>skills attempted</span></div><div><strong>${priority}</strong><span>skills needing attention</span></div></div></section><section class="panel"><h2>Suggested workflow</h2><div class="workflow"><div><strong>1. Diagnose</strong><p>Take a fixed exam form without notes.</p></div><div><strong>2. Target</strong><p>Use the weakness report to open the lowest-scoring skill quizzes.</p></div><div><strong>3. Learn</strong><p>Read the explanation for every missed question.</p></div><div><strong>4. Verify</strong><p>Return to a different fixed exam form and compare.</p></div></div></section></section>`;}
function skillCard(s,mastery){const buttons=[1,2,3].map(v=>`<button class="secondary-button" data-action="start-skill" data-skill="${s.id}" data-version="${v}">Version ${v}</button>`).join('');return `<article class="skill-card">${s.group?`<span class="chip">${esc(s.group)}</span>`:''}<div class="skill-title-row"><h3>${esc(s.label)}</h3>${masteryBadge(mastery)}</div><p>${esc(s.description)}</p><div class="skill-meta">${s.quizCount} questions per fixed version • ${s.poolCount}-question bank${mastery&&mastery.total?` • ${mastery.correct}/${mastery.total} cumulative correct`:''}</div><div class="skill-actions">${buttons}<button class="ghost-button" data-action="start-skill" data-skill="${s.id}" data-version="random">Random</button></div></article>`;}
function examPage(id){const e=D.exams[id];if(!e)return go('home');const m=masteryMap();const fixed=['A','B','C','D'].map((x,i)=>`<button class="form-button" data-action="start-exam" data-exam="${id}" data-form="${i}"><strong>Form ${x}</strong><small>${e.examCount} questions • fixed, reproducible</small></button>`).join('');const skills=e.skills.map(sid=>skillCard(D.skills[sid],m[sid])).join('');main.innerHTML=`<section class="content-wrap"><div class="breadcrumbs"><button data-action="home">Home</button><span>›</span>Exam ${esc(e.number)}</div><div class="exam-detail"><div><p class="eyebrow">Diagnostic Exam ${esc(e.number)}</p><h1>${esc(e.title)}</h1><p>${esc(e.description)}</p></div><span class="chip">${e.skills.length} reporting skills</span></div><section class="panel"><h2>Diagnostic forms</h2><p>Forms A–D are disjoint within this exam. A submitted exam produces a skill-by-skill weakness report.</p><div class="form-list">${fixed}<button class="form-button" data-action="start-exam" data-exam="${id}" data-form="random"><strong>Random form</strong><small>${e.examCount} questions • fresh balanced draw</small></button></div></section><div class="section-heading"><h2>Focused skill quizzes</h2><p>Fixed Versions 1–3 are nonoverlapping within each skill. Random draws from the full skill bank.</p></div><div class="skill-grid">${skills}</div></section>`;}

function fixedSkillQuestions(sid,version){const s=D.skills[sid],pool=D.questions[sid];const start=(version-1)*s.quizCount;return pool.slice(start,start+s.quizCount);}
function randomSkillQuestions(sid){const s=D.skills[sid],pool=D.questions[sid];return shuffle(pool,rng(`${sid}:random:${Date.now()}:${Math.random()}`)).slice(0,s.quizCount);}
function examAllocation(e){if(e.allocation)return e.skills.map(sid=>({sid,count:e.allocation[sid]||0})).filter(x=>x.count>0);const n=e.skills.length,base=Math.floor(e.examCount/n),rem=e.examCount%n;return e.skills.map((sid,i)=>({sid,count:base+(i<rem?1:0)}));}
function balancedDraw(pool,count,seed,blockedIds=new Set()){const candidates=shuffle(pool.filter(q=>!blockedIds.has(q.id)),rng(seed));const groups=[...new Set(candidates.map(q=>q.diagnosticGroup).filter(Boolean))];if(groups.length<2)return candidates.slice(0,count);const selected=[],selectedIds=new Set(),usedVariants=new Set(),groupCounts={};while(selected.length<count){let best=null,bestScore=Infinity;for(let i=0;i<candidates.length;i++){const q=candidates[i];if(selectedIds.has(q.id))continue;const g=q.diagnosticGroup||'general',gc=groupCounts[g]||0;const v=q.diagnosticVariant;const variantPenalty=v!==undefined&&usedVariants.has(String(v))?1:0;const score=gc*100+variantPenalty*10+i/candidates.length;if(score<bestScore){best=q;bestScore=score;}}if(!best)break;selected.push(best);selectedIds.add(best.id);groupCounts[best.diagnosticGroup||'general']=(groupCounts[best.diagnosticGroup||'general']||0)+1;if(best.diagnosticVariant!==undefined)usedVariants.add(String(best.diagnosticVariant));}return selected;}
function fixedExamSkillQuestions(e,sid,count,form){const used=new Set();let chosen=[];for(let f=0;f<=form;f++){chosen=balancedDraw(D.questions[sid],count,`${e.id}:${sid}:balanced:${f}`,used);chosen.forEach(q=>used.add(q.id));}return chosen;}
function fixedExamQuestions(e,form){let out=[];for(const a of examAllocation(e))out.push(...fixedExamSkillQuestions(e,a.sid,a.count,form));return shuffle(out,rng(`${e.id}:form:${form}:mix`));}
function randomExamQuestions(e){let out=[];for(const a of examAllocation(e))out.push(...balancedDraw(D.questions[a.sid],a.count,`${e.id}:${a.sid}:random:${Date.now()}:${Math.random()}`));return shuffle(out,rng(`${e.id}:random-mix:${Date.now()}`));}
function startSkill(sid,version){const s=D.skills[sid];const qs=version==='random'?randomSkillQuestions(sid):fixedSkillQuestions(sid,Number(version));startQuiz({mode:'skill',examId:s.exam,skillId:sid,label:`${s.label} — ${version==='random'?'Random':`Version ${version}`}`,questions:qs});}
function startExam(id,form){const e=D.exams[id];const qs=form==='random'?randomExamQuestions(e):fixedExamQuestions(e,Number(form));startQuiz({mode:'exam',examId:id,skillId:null,label:`Exam ${e.number}: ${e.title} — ${form==='random'?'Random':`Form ${String.fromCharCode(65+Number(form))}`}`,questions:qs});}
function startQuiz(o){state.quiz={...o,answers:Array(o.questions.length).fill(null),flags:Array(o.questions.length).fill(false),current:0,startedAt:Date.now()};state.result=null;state.view='quiz';window.scrollTo(0,0);quizPage();}
function quizPage(){const z=state.quiz,q=z.questions[z.current],answered=z.answers.filter(x=>x!==null).length;main.innerHTML=`<section class="quiz-shell"><div class="quiz-top"><div><p class="eyebrow">${esc(z.mode==='exam'?'Diagnostic exam':'Focused skill quiz')}</p><h1>${esc(z.label)}</h1></div><button class="danger-outline" data-action="exit-quiz">Exit</button></div><div class="quiz-status"><span>Question <strong>${z.current+1}</strong> of ${z.questions.length}</span><span>${answered} answered</span></div><div class="progress-track"><span style="width:${((z.current+1)/z.questions.length)*100}%"></span></div><article class="question-card"><div class="question-prompt">${q.prompt}</div><div class="choices">${q.choices.map((c,i)=>`<label class="choice ${z.answers[z.current]===i?'selected':''}"><input type="radio" name="answer" value="${i}" ${z.answers[z.current]===i?'checked':''}><span class="choice-letter">${String.fromCharCode(65+i)}</span><span>${c}</span></label>`).join('')}</div></article><div class="quiz-controls"><button class="secondary-button" data-action="prev" ${z.current===0?'disabled':''}>Previous</button><button class="ghost-button" data-action="flag">${z.flags[z.current]?'★ Flagged':'☆ Flag question'}</button>${z.current<z.questions.length-1?'<button class="primary-button" data-action="next">Next</button>':'<button class="primary-button" data-action="submit">Submit quiz</button>'}</div><div class="question-nav">${z.questions.map((_,i)=>`<button data-action="jump" data-index="${i}" class="${i===z.current?'current':''} ${z.answers[i]!==null?'answered':''} ${z.flags[i]?'flagged':''}">${i+1}</button>`).join('')}</div></section>`;typeset();}
function submitQuiz(){const z=state.quiz;const rows=z.questions.map((q,i)=>({q,chosen:z.answers[i],correct:z.answers[i]===q.answer}));const correct=rows.filter(x=>x.correct).length;const skillMap={};for(const row of rows){const sid=row.q.skill;if(!skillMap[sid])skillMap[sid]={id:sid,label:D.skills[sid].label,correct:0,total:0};skillMap[sid].total++;if(row.correct)skillMap[sid].correct++;}const skillStats=Object.values(skillMap).map(x=>({...x,percent:Math.round(100*x.correct/x.total)})).sort((a,b)=>a.percent-b.percent||a.label.localeCompare(b.label));state.result={id:`${Date.now()}`,mode:z.mode,examId:z.examId,skillId:z.skillId,label:z.label,correct,total:rows.length,percent:Math.round(100*correct/rows.length),rows,skillStats,completedAt:new Date().toISOString(),durationSeconds:Math.floor((Date.now()-z.startedAt)/1000)};record(state.result);state.view='results';state.quiz=null;window.scrollTo(0,0);resultsPage();}
function scoreClass(p){return p>=80?'good':p>=65?'mid':'weak';}
function resultsPage(){const r=state.result;const e=D.exams[r.examId];const report=r.mode==='exam'?`<section class="panel"><h2>Weakness report</h2><p>Lower-scoring skills are listed first. Use the practice button to work that exact skill.</p><div class="weakness-list">${r.skillStats.map(s=>`<div class="weak-row"><div><strong>${esc(s.label)}</strong><span>${s.correct}/${s.total} correct</span></div><div class="meter"><span class="${scoreClass(s.percent)}" style="width:${s.percent}%"></span></div><strong>${s.percent}%</strong><button class="secondary-button" data-action="start-skill" data-skill="${s.id}" data-version="1">Practice</button></div>`).join('')}</div></section>`:'';main.innerHTML=`<section class="content-wrap"><div class="results-hero"><p class="eyebrow">Results</p><h1>${esc(r.label)}</h1><div class="score-ring ${scoreClass(r.percent)}"><strong>${r.percent}%</strong><span>${r.correct}/${r.total} correct</span></div><div class="result-actions"><button class="primary-button" data-action="open-exam" data-exam="${r.examId}">Back to Exam ${esc(e.number)}</button><button class="secondary-button" data-action="progress">My progress</button></div></div>${report}<section><div class="section-heading"><h2>Question review</h2><p>Each question shows your answer, the correct answer, and an explanation.</p><div class="filter-buttons"><button class="${state.filter==='all'?'active':''}" data-action="filter" data-filter="all">All</button><button class="${state.filter==='missed'?'active':''}" data-action="filter" data-filter="missed">Missed only</button></div></div><div class="review-list">${r.rows.map((row,i)=>review(row,i)).join('')}</div></section></section>`;typeset();}
function review(row,i){if(state.filter==='missed'&&row.correct)return'';const q=row.q;const chosen=row.chosen===null?'No answer':q.choices[row.chosen];return `<article class="review-card ${row.correct?'correct':'incorrect'}"><div class="review-head"><strong>Question ${i+1}</strong><span>${row.correct?'✓ Correct':'✕ Review'}</span></div><div class="question-prompt">${q.prompt}</div><div class="answer-lines"><p><strong>Your answer:</strong> ${chosen}</p><p><strong>Correct answer:</strong> ${q.choices[q.answer]}</p></div><div class="explanation"><strong>Explanation</strong><p>${q.explanation}</p></div><div class="review-skill">Skill: ${esc(D.skills[q.skill].label)}</div></article>`;}
function progressPage(){const a=loadResults(),m=masteryMap(),weak=cumulativeWeaknesses(m),attempted=weak.length;const history=a.length?a.map(x=>`<tr><td>${new Date(x.completedAt).toLocaleString()}</td><td>${esc(x.label)}</td><td>${x.score}/${x.total}</td><td>${x.percent}%</td></tr>`).join(''):'<tr><td colspan="4">No completed quizzes yet.</td></tr>';const priority=weak.slice(0,5);main.innerHTML=`<section class="content-wrap"><div class="breadcrumbs"><button data-action="home">Home</button><span>›</span>Progress</div><div class="section-heading"><div><p class="eyebrow">Stored on this device</p><h1>Progress and skill history</h1><p>Results remain in this browser. Clearing browser storage or using another device will not carry the history over.</p></div></div><div class="progress-summary-grid"><div><strong>${a.length}</strong><span>activities completed</span></div><div><strong>${attempted}/${Object.keys(D.skills).length}</strong><span>skills attempted</span></div><div><strong>${weak.filter(([,x])=>x.percent>=80).length}</strong><span>skills currently strong</span></div></div>${priority.length?`<section class="panel"><div class="section-heading"><div><h2>Cumulative priorities</h2><p>Lowest performance across all saved attempts.</p></div></div><div class="priority-grid">${priority.map(([id,x])=>`<div class="priority-item"><div><strong>${esc(D.skills[id].label)}</strong>${masteryBadge(x)}<small>${x.correct}/${x.total} correct across ${x.attempts} activities</small></div><button class="secondary-button" data-action="start-skill" data-skill="${id}" data-version="random">Practice</button></div>`).join('')}</div></section>`:''}<section class="panel"><div class="section-heading"><div><h2>Skill mastery</h2><p>All saved questions are combined by skill.</p></div></div><div class="mastery-grid">${Object.entries(D.skills).map(([id,s])=>`<div class="mastery-item"><strong>${esc(s.label)}</strong>${masteryBadge(m[id])}<span>${m[id].total?`${m[id].correct}/${m[id].total} correct across ${m[id].attempts} activities`:'No score data yet'}</span></div>`).join('')}</div></section><section class="panel"><div class="section-heading"><h2>Activity history</h2>${a.length?'<button class="danger-outline" data-action="clear-progress">Clear progress history</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Activity</th><th>Score</th><th>Percent</th></tr></thead><tbody>${history}</tbody></table></div></section></section>`;}
function aboutPage(){main.innerHTML=`<section class="content-wrap narrow"><div class="breadcrumbs"><button data-action="home">Home</button><span>›</span>About</div><h1>About this practice center</h1><p>This site is organized around the course review sequence. Diagnostic exams report performance by focused skill so students can move directly from a weak area to targeted practice.</p><p>Mathematical notation is rendered consistently with MathJax. Hypothesis-testing practice uses the P-value method. Setup and interpretation are practiced separately from contextual P-value calculations, so students can work on each part of a hypothesis test independently.</p><p>Monetary variables such as salary and posted prices may be classified as discrete when the possible values occur in fixed currency increments.</p></section>`;}

document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='home')go('home');else if(a==='open-exam')go('exam',{examId:b.dataset.exam});else if(a==='progress')go('progress');else if(a==='about')go('about');else if(a==='start-skill')startSkill(b.dataset.skill,b.dataset.version);else if(a==='start-exam')startExam(b.dataset.exam,b.dataset.form);else if(a==='exit-quiz')go('exam',{examId:state.quiz.examId});else if(a==='prev'){state.quiz.current--;quizPage();}else if(a==='next'){state.quiz.current++;quizPage();}else if(a==='jump'){state.quiz.current=Number(b.dataset.index);quizPage();}else if(a==='flag'){state.quiz.flags[state.quiz.current]=!state.quiz.flags[state.quiz.current];quizPage();}else if(a==='submit')submitQuiz();else if(a==='filter'){state.filter=b.dataset.filter;resultsPage();}else if(a==='clear-progress'){if(confirm('Clear all stored progress?')){saveResults([]);progressPage();}}});
document.addEventListener('change',e=>{if(e.target.name==='answer'&&state.quiz){state.quiz.answers[state.quiz.current]=Number(e.target.value);quizPage();}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(state.quiz){if(['1','2','3','4'].includes(e.key)){const idx=Number(e.key)-1;if(idx<state.quiz.questions[state.quiz.current].choices.length){state.quiz.answers[state.quiz.current]=idx;quizPage();}}else if(e.key==='ArrowRight'&&state.quiz.current<state.quiz.questions.length-1){state.quiz.current++;quizPage();}else if(e.key==='ArrowLeft'&&state.quiz.current>0){state.quiz.current--;quizPage();}}});
document.querySelector('.brand').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go('home');}});
render();
})();
