(function(){
"use strict";
const DB_KEY="practiceInstructorDashboard.v1";
const DB_SCHEMA=1;
let db=loadDb(), activeStudentKey=null;
const selectedStudentKeys=new Set();
const $=s=>document.querySelector(s);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function normalizeName(v){return String(v||"").trim().replace(/\s+/g," ").toLocaleLowerCase();}
function normalizeId(v){return String(v||"").trim().replace(/\s+/g," ").toLocaleLowerCase();}
function loadDb(){try{const x=JSON.parse(localStorage.getItem(DB_KEY)||"");if(x&&x.schemaVersion===DB_SCHEMA&&Array.isArray(x.students)){x.settings=x.settings||{};return x;}}catch{}return {schemaVersion:DB_SCHEMA,students:[],settings:{siteFilter:"all"}};}
function saveDb(){localStorage.setItem(DB_KEY,JSON.stringify(db));}
function uid(){return crypto?.randomUUID?.()||`s-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
function fmtDate(v,short=false){if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return short?d.toLocaleDateString():d.toLocaleString();}
function pct(n,d){return d?Math.round(100*n/d):null;}
function sites(){const m=new Map();for(const s of db.students)for(const r of Object.values(s.records||{}))m.set(r.site.id,r.site.title);return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1]));}
function selectedSite(){return $("#site-filter")?.value||"all";}
function recordsFor(student,site=selectedSite()){const records=Object.values(student.records||{});return site==="all"?records:records.filter(r=>r.site.id===site);}
function studentTotals(student,site=selectedSite()){const records=recordsFor(student,site),totalCorrect=records.reduce((n,r)=>n+(Number(r.summary?.totalCorrect)||0),0),totalQuestions=records.reduce((n,r)=>n+(Number(r.summary?.totalQuestions)||0),0),activities=records.reduce((n,r)=>n+(Number(r.summary?.activitiesCompleted)||0),0),needs=records.reduce((n,r)=>n+(Number(r.summary?.needsAttentionCount)||0),0),last=records.map(r=>r.summary?.lastActivityAt).filter(Boolean).sort().at(-1)||null;return {records,totalCorrect,totalQuestions,activities,needs,overall:pct(totalCorrect,totalQuestions),last};}
function validProgress(x){return x&&x.schema==="practice-progress-export"&&Number(x.schemaVersion)===1&&x.student&&String(x.student.name||"").trim()&&x.site&&String(x.site.id||"").trim()&&Array.isArray(x.areas)&&Array.isArray(x.attempts)&&x.summary;}
function findStudentForProgress(p){const nid=normalizeId(p.student.studentId),nn=normalizeName(p.student.name);if(nid){const byId=db.students.find(s=>normalizeId(s.studentId)===nid);if(byId)return byId;const nameNoId=db.students.filter(s=>!s.studentId&&normalizeName(s.name)===nn);if(nameNoId.length===1){nameNoId[0].studentId=String(p.student.studentId).trim();return nameNoId[0];}return null;}const sameName=db.students.filter(s=>normalizeName(s.name)===nn);return sameName.length===1?sameName[0]:null;}
function syncStudentIdentity(s){for(const r of Object.values(s.records||{})){r.student=r.student||{};r.student.name=s.name;r.student.studentId=s.studentId||null;r.student.normalizedName=normalizeName(s.name);r.student.normalizedStudentId=s.studentId?normalizeId(s.studentId):null;}}
function addProgress(p){let s=findStudentForProgress(p),created=false;if(!s){s={key:uid(),name:p.student.name.trim().replace(/\s+/g," "),studentId:String(p.student.studentId||"").trim(),records:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.students.push(s);created=true;}else{if(p.student.studentId&&!s.studentId)s.studentId=String(p.student.studentId).trim();if(p.student.name)s.name=p.student.name.trim().replace(/\s+/g," ");}
  s.records=s.records||{};const old=s.records[p.site.id];if(old&&String(old.exportedAt||"")>String(p.exportedAt||""))return {kind:"older",student:s,site:p.site.title};s.records[p.site.id]=p;syncStudentIdentity(s);s.updatedAt=new Date().toISOString();return {kind:created?"added":old?"updated":"site-added",student:s,site:p.site.title};}
async function readFileJson(file){const text=await file.text();return JSON.parse(text);}
async function importStudentFiles(files){let added=0,updated=0,older=0,invalid=0,errors=[];for(const file of files){try{const x=await readFileJson(file);if(!validProgress(x)){invalid++;continue;}const r=addProgress(x);if(r.kind==="older")older++;else if(r.kind==="added"||r.kind==="site-added")added++;else updated++;}catch(e){errors.push(file.name);}}
  saveDb();render();const bits=[];if(added)bits.push(`${added} added`);if(updated)bits.push(`${updated} replaced with newer progress`);if(older)bits.push(`${older} older file${older===1?"":"s"} skipped`);if(invalid)bits.push(`${invalid} invalid progress file${invalid===1?"":"s"}`);if(errors.length)bits.push(`${errors.length} unreadable file${errors.length===1?"":"s"}`);setMessage("#import-message",bits.length?bits.join("; ")+".":"No files were imported.",invalid||errors.length?"warn":"success");}
function setMessage(sel,text,cls=""){const el=$(sel);if(!el)return;el.textContent=text;el.className=`message ${cls}`;}
function renderSiteFilter(){const sel=$("#site-filter"),current=db.settings.siteFilter||sel.value||"all";sel.innerHTML='<option value="all">All sites</option>'+sites().map(([id,title])=>`<option value="${esc(id)}">${esc(title)}</option>`).join("");sel.value=[...sel.options].some(o=>o.value===current)?current:"all";}
function renderSummary(){const site=selectedSite(),students=db.students.filter(s=>recordsFor(s,site).length),totals=students.map(s=>studentTotals(s,site)),activities=totals.reduce((n,x)=>n+x.activities,0),correct=totals.reduce((n,x)=>n+x.totalCorrect,0),questions=totals.reduce((n,x)=>n+x.totalQuestions,0),needs=totals.reduce((n,x)=>n+x.needs,0),last=totals.map(x=>x.last).filter(Boolean).sort().at(-1)||null;$("#summary").innerHTML=`<div class="metric"><strong>${students.length}</strong><span>students</span></div><div class="metric"><strong>${activities}</strong><span>activities</span></div><div class="metric"><strong>${pct(correct,questions)??"—"}${questions?"%":""}</strong><span>combined accuracy</span></div><div class="metric"><strong>${needs}</strong><span>student-area weaknesses</span></div><div class="metric"><strong>${fmtDate(last,true)}</strong><span>latest activity</span></div>`;}
function visibleStudents(){const site=selectedSite(),q=normalizeName($("#student-search").value);return db.students.filter(s=>recordsFor(s,site).length).filter(s=>!q||normalizeName(`${s.name} ${s.studentId||""}`).includes(q)).sort((a,b)=>a.name.localeCompare(b.name));}
function pruneSelection(){const valid=new Set(db.students.map(s=>s.key));for(const key of [...selectedStudentKeys])if(!valid.has(key))selectedStudentKeys.delete(key);}
function updateBulkActions(){pruneSelection();const n=selectedStudentKeys.size,btn=$("#delete-selected");if(btn){btn.disabled=!n;btn.textContent=`Delete selected (${n})`;}const clear=$("#clear-selection");if(clear)clear.disabled=!n;}
function renderStudents(){const site=selectedSite(),rows=visibleStudents();$("#student-table").innerHTML=rows.length?rows.map(s=>{const t=studentTotals(s,site),checked=selectedStudentKeys.has(s.key)?" checked":"";return `<tr><td class="select-col"><input type="checkbox" class="student-select" data-select-student="${s.key}" aria-label="Select ${esc(s.name)}"${checked}></td><td><button class="student-link" data-student="${s.key}">${esc(s.name)}</button></td><td>${s.studentId?esc(s.studentId):'<span class="small">Not provided</span>'}</td><td>${t.records.map(r=>`<span class="tag">${esc(r.site.title)}</span>`).join("")}</td><td>${t.activities}</td><td class="${t.overall==null?'':t.overall>=80?'status-good':t.overall>=60?'status-warn':'status-bad'}">${t.overall??"—"}${t.overall==null?"":"%"}</td><td class="${t.needs?'status-bad':''}">${t.needs}</td><td>${fmtDate(t.last,true)}</td><td><div class="row-actions"><button class="button secondary" data-student="${s.key}">View</button><button class="button danger" data-delete="${s.key}">Delete</button></div></td></tr>`;}).join(""):'<tr><td colspan="9" class="empty">No student records match this view.</td></tr>';updateBulkActions();}
function areaAggregates(){const site=selectedSite(),map={};for(const s of db.students)for(const r of recordsFor(s,site))for(const a of r.areas||[]){if(!(Number(a.total)>0))continue;const key=`${r.site.id}::${a.id}`,x=map[key]??={siteId:r.site.id,siteTitle:r.site.title,areaId:a.id,label:a.label,correct:0,total:0,students:new Set(),needs:0,developing:0,strong:0};x.correct+=Number(a.correct)||0;x.total+=Number(a.total)||0;x.students.add(s.key);if(Number(a.percent)<60)x.needs++;else if(Number(a.percent)<80)x.developing++;else x.strong++;map[key]=x;}return Object.values(map).sort((a,b)=>{const pa=pct(a.correct,a.total)??101,pb=pct(b.correct,b.total)??101;return pa-pb||a.siteTitle.localeCompare(b.siteTitle)||a.label.localeCompare(b.label);});}
function renderAreas(){const all=areaAggregates(),specific=selectedSite()!=="all";$("#area-table").innerHTML=all.length?all.map(x=>{const p=pct(x.correct,x.total);return `<tr><td>${specific?"":`<span class="tag">${esc(x.siteTitle)}</span><br>`}<strong>${esc(x.label)}</strong></td><td>${x.students.size}</td><td>${x.correct}/${x.total}</td><td class="${p>=80?'status-good':p>=60?'status-warn':'status-bad'}">${p}%</td><td class="${x.needs?'status-bad':''}">${x.needs}</td><td class="${x.developing?'status-warn':''}">${x.developing}</td><td class="${x.strong?'status-good':''}">${x.strong}</td></tr>`;}).join(""):'<tr><td colspan="7" class="empty">No attempted areas are available for this view.</td></tr>';}
function render(){renderSiteFilter();renderSummary();renderStudents();renderAreas();}
function openStudent(key){const s=db.students.find(x=>x.key===key);if(!s)return;activeStudentKey=key;$("#dialog-title").textContent=s.name;$("#edit-name").value=s.name;$("#edit-id").value=s.studentId||"";$("#dialog-message").textContent="";$("#student-detail").innerHTML=Object.values(s.records||{}).sort((a,b)=>a.site.title.localeCompare(b.site.title)).map(r=>{const attempted=(r.areas||[]).filter(a=>a.total>0).sort((a,b)=>(a.percent??101)-(b.percent??101)),history=(r.attempts||[]).slice().sort((a,b)=>String(b.completedAt||"").localeCompare(String(a.completedAt||"")));return `<section class="site-detail"><h3>${esc(r.site.title)}</h3><p class="small">Exported ${esc(fmtDate(r.exportedAt))}</p><div class="detail-summary"><span class="tag">${r.summary.activitiesCompleted} activities</span><span class="tag">${r.summary.overallPercent??"—"}${r.summary.overallPercent==null?"":"%"} overall</span><span class="tag">${r.summary.needsAttentionCount} need attention</span></div><h4>Skill / component mastery</h4><div class="table-wrap"><table class="mini-table"><thead><tr><th>Area</th><th>Score</th><th>Percent</th><th>Status</th></tr></thead><tbody>${attempted.length?attempted.map(a=>`<tr><td>${esc(a.label)}</td><td>${a.correct}/${a.total}</td><td>${a.percent}%</td><td class="${a.percent>=80?'status-good':a.percent>=60?'status-warn':'status-bad'}">${esc(a.status||"")}</td></tr>`).join(""):'<tr><td colspan="4">No attempted areas.</td></tr>'}</tbody></table></div><details class="activity-detail" ${history.length<=8?'open':''}><summary>Individual tests / activities (${history.length})</summary><div class="table-wrap"><table class="mini-table activity-table"><thead><tr><th>Date</th><th>Test / activity</th><th>Type</th><th>Score</th><th>Percent</th></tr></thead><tbody>${history.length?history.map(a=>`<tr><td>${esc(fmtDate(a.completedAt,true))}</td><td>${esc(a.label||"Practice activity")}</td><td>${esc(String(a.activityType||"practice").replace(/[-_]/g," "))}</td><td>${Number(a.correct)||0}/${Number(a.total)||0}</td><td>${Number(a.percent)||0}%</td></tr>`).join(""):'<tr><td colspan="5">No completed activity history.</td></tr>'}</tbody></table></div></details></section>`;}).join("")||'<p class="empty">No site records.</p>';$("#student-dialog").showModal();}
function deleteStudent(key){const s=db.students.find(x=>x.key===key);if(!s)return;if(!confirm(`Delete ${s.name} and all imported progress for this student?`))return;db.students=db.students.filter(x=>x.key!==key);selectedStudentKeys.delete(key);saveDb();if($("#student-dialog").open)$("#student-dialog").close();render();}
function selectVisibleStudents(){for(const s of visibleStudents())selectedStudentKeys.add(s.key);renderStudents();}
function clearStudentSelection(){selectedStudentKeys.clear();renderStudents();}
function deleteSelectedStudents(){const keys=[...selectedStudentKeys].filter(key=>db.students.some(s=>s.key===key));if(!keys.length)return;const names=keys.map(key=>db.students.find(s=>s.key===key)?.name).filter(Boolean);const detail=keys.length<=5?`\n\n${names.join("\n")}`:"";if(!confirm(`Delete ${keys.length} selected student${keys.length===1?"":"s"} and all imported progress for ${keys.length===1?"this student":"these students"}?${detail}`))return;const remove=new Set(keys);db.students=db.students.filter(s=>!remove.has(s.key));selectedStudentKeys.clear();saveDb();if($("#student-dialog").open&&remove.has(activeStudentKey))$("#student-dialog").close();render();setMessage("#import-message",`${keys.length} student${keys.length===1?"":"s"} deleted from this dashboard.`,"success");}
function identityMatch(name,id,excludeKey){const candidates=db.students.filter(s=>s.key!==excludeKey),nid=normalizeId(id),nn=normalizeName(name);if(nid)return candidates.find(s=>normalizeId(s.studentId)===nid)||null;const sameName=candidates.filter(s=>normalizeName(s.name)===nn);return sameName.length===1?sameName[0]:null;}
function mergeStudents(target,source){target.records=target.records||{};for(const [siteId,r] of Object.entries(source.records||{})){const old=target.records[siteId];if(!old||String(r.exportedAt||"")>=String(old.exportedAt||""))target.records[siteId]=r;}if(!target.studentId&&source.studentId)target.studentId=source.studentId;syncStudentIdentity(target);target.updatedAt=new Date().toISOString();db.students=db.students.filter(s=>s.key!==source.key);}
function saveIdentity(){const s=db.students.find(x=>x.key===activeStudentKey);if(!s)return;const name=$("#edit-name").value.trim().replace(/\s+/g," "),id=$("#edit-id").value.trim();if(!name){setMessage("#dialog-message","Student name is required.","error");$("#edit-name").focus();return;}const other=identityMatch(name,id,s.key);if(other){if(!confirm(`This identity matches ${other.name}. Merge the two student records?`))return;s.name=name;s.studentId=id;mergeStudents(other,s);activeStudentKey=other.key;saveDb();render();openStudent(other.key);setMessage("#dialog-message","Student records merged.","success");return;}s.name=name;s.studentId=id;syncStudentIdentity(s);s.updatedAt=new Date().toISOString();saveDb();render();$("#dialog-title").textContent=name;setMessage("#dialog-message","Student identity saved. Student ID may remain blank.","success");}
function exportBackup(){const out={schema:"practice-instructor-backup",schemaVersion:1,exportedAt:new Date().toISOString(),dashboard:{schemaVersion:db.schemaVersion,students:db.students,settings:db.settings}};const blob=new Blob([JSON.stringify(out,null,2)+"\n"],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`practice_progress_backup_${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function validBackup(x){if(!(x&&x.schema==="practice-instructor-backup"&&Number(x.schemaVersion)===1&&x.dashboard&&Array.isArray(x.dashboard.students)))return false;return x.dashboard.students.every(s=>s&&String(s.name||"").trim()&&s.records&&typeof s.records==="object"&&!Array.isArray(s.records)&&Object.values(s.records).every(validProgress));}
function clone(v){return JSON.parse(JSON.stringify(v));}
function mergeBackup(back){let counts={students:0,records:0};for(const incoming of back.dashboard.students){let target=null;if(incoming.studentId){target=db.students.find(s=>normalizeId(s.studentId)===normalizeId(incoming.studentId));if(!target){const ms=db.students.filter(s=>!s.studentId&&normalizeName(s.name)===normalizeName(incoming.name));if(ms.length===1){target=ms[0];target.studentId=incoming.studentId;}}}else{const ms=db.students.filter(s=>normalizeName(s.name)===normalizeName(incoming.name));if(ms.length===1)target=ms[0];}if(!target){db.students.push(clone(incoming));counts.students++;continue;}for(const [siteId,r] of Object.entries(incoming.records||{})){const old=target.records?.[siteId];target.records=target.records||{};if(!old||String(r.exportedAt||"")>=String(old.exportedAt||"")){target.records[siteId]=clone(r);counts.records++;}}syncStudentIdentity(target);target.updatedAt=new Date().toISOString();}return counts;}
async function restoreBackup(file){try{const x=await readFileJson(file);if(!validBackup(x)){alert("That file is not a valid instructor dashboard backup.");return;}const mode=$("#restore-mode").value;if(mode==="replace"){if(!confirm("Replace all current instructor dashboard data with this backup?"))return;db={schemaVersion:DB_SCHEMA,students:clone(x.dashboard.students),settings:clone(x.dashboard.settings||{})};}else{mergeBackup(x);}saveDb();render();alert(mode==="replace"?"Instructor dashboard restored from backup.":"Backup merged with the current instructor dashboard. Newer site records were retained.");}catch(e){console.error(e);alert("The backup file could not be read.");}}
$("#student-files").addEventListener("change",e=>{const files=[...e.target.files];e.target.value="";if(files.length)importStudentFiles(files);});
$("#export-backup").addEventListener("click",exportBackup);
$("#restore-backup").addEventListener("change",e=>{const f=e.target.files[0];e.target.value="";if(f)restoreBackup(f);});
$("#site-filter").addEventListener("change",()=>{db.settings.siteFilter=selectedSite();saveDb();renderSummary();renderStudents();renderAreas();});
$("#student-search").addEventListener("input",renderStudents);
$("#select-visible").addEventListener("click",selectVisibleStudents);
$("#clear-selection").addEventListener("click",clearStudentSelection);
$("#delete-selected").addEventListener("click",deleteSelectedStudents);
document.addEventListener("change",e=>{const box=e.target.closest("[data-select-student]");if(!box)return;if(box.checked)selectedStudentKeys.add(box.dataset.selectStudent);else selectedStudentKeys.delete(box.dataset.selectStudent);updateBulkActions();});
document.addEventListener("click",e=>{const view=e.target.closest("[data-student]"),del=e.target.closest("[data-delete]");if(del){deleteStudent(del.dataset.delete);return;}if(view)openStudent(view.dataset.student);});
$("#save-identity").addEventListener("click",saveIdentity);
$("#delete-student").addEventListener("click",()=>activeStudentKey&&deleteStudent(activeStudentKey));
render();
})();
