const fs=require('fs'),vm=require('vm'),path=require('path');
const dir=__dirname,ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(dir,'content.js'),'utf8'),ctx);const D=ctx.window.STAAR7_DATA;
const errors=[],warnings=[],qmap=new Map(D.questions.map(q=>[q.id,q]));
const norm=s=>String(s??'').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim().toLowerCase();
const fp=q=>[norm(q.stimulus),...(q.passageIds||[]),norm(q.prompt),norm(Array.isArray(q.correct)?q.correct.join('|'):q.correct),...(q.distractors||[]).map(norm)].join('||');
function hashString(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rngFrom(seed){let a=hashString(String(seed));return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function shuffled(arr,rng){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const fullIds=new Set(D.forms.flatMap(f=>f.itemIds.filter(id=>!id.startsWith('ecr'))));
const fullFps=new Set([...fullIds].map(id=>qmap.has(id)?fp(qmap.get(id)):null).filter(Boolean));
function pool(skillId){const seen=new Set(),out=[];for(const q of D.questions.filter(x=>x.skill===skillId)){const k=fp(q);if(fullFps.has(k)||seen.has(k))continue;seen.add(k);out.push(q);}return out;}
function sets(skillId){const s=D.skills[skillId];if(s.mode==='ecr')return D.ecrPrompts.filter(x=>x.skill===skillId).slice(0,4).map(x=>[x]);const p=shuffled(pool(skillId),rngFrom(`${skillId}-distinct-fixed-v3`));if(!p.length)return[];const n=Math.min(4,Math.max(1,Math.floor(p.length/4))),base=Math.floor(p.length/n),extra=p.length%n,out=[];let at=0;for(let i=0;i<n;i++){const size=base+(i<extra?1:0);out.push(p.slice(at,at+size));at+=size;}return out;}
// Basic question integrity
for(const q of D.questions){if(!D.skills[q.skill])errors.push(`Unknown skill ${q.skill} on ${q.id}`);const correct=Array.isArray(q.correct)?q.correct:[q.correct];const choices=[...correct,...q.distractors];if(new Set(choices).size!==choices.length)errors.push(`Duplicate choices ${q.id}`);if(!q.explanation)errors.push(`Missing explanation ${q.id}`);}
// Forms
const formSummary=[];const across=new Set();for(const f of D.forms){let pts=0,read=0,write=0,two=0,ecr=0;const local=new Set();for(const id of f.itemIds){if(id.startsWith('ecr')){const e=D.ecrPrompts.find(x=>x.id===id);if(!e){errors.push(`Missing ECR ${id}`);continue;}pts+=10;write++;ecr++;continue;}const q=qmap.get(id);if(!q){errors.push(`Missing question ${id} in form ${f.id}`);continue;}const k=fp(q);if(local.has(k))errors.push(`Repeated content within Form ${f.id}: ${id}`);local.add(k);if(across.has(k))errors.push(`Repeated content across fixed forms: ${id}`);across.add(k);pts+=q.points||1;if((q.points||1)===2)two++;if(q.category==='Reading')read++;else write++;}
if(f.itemIds.length!==45)errors.push(`Form ${f.id} has ${f.itemIds.length} items`);if(pts!==56)errors.push(`Form ${f.id} has ${pts} points`);if(read<26||read>28)errors.push(`Form ${f.id} reading count ${read}`);if(write<17||write>19)errors.push(`Form ${f.id} writing count ${write}`);if(two!==2)errors.push(`Form ${f.id} has ${two} two-point items`);if(ecr!==1)errors.push(`Form ${f.id} has ${ecr} ECR items`);formSummary.push({form:f.id,items:f.itemIds.length,points:pts,reading:read,writing:write,twoPoint:two,ecr});}
// Skill pools and fixed-set independence
const skillSummary=[];for(const [sid,s] of Object.entries(D.skills)){if(s.mode==='ecr'){const n=D.ecrPrompts.filter(x=>x.skill===sid).length;if(!n)errors.push(`No writing prompt for ${sid}`);skillSummary.push({skill:sid,tested:s.tested,mode:'ecr',practiceUnique:n,fixedSets:Math.min(4,n)});continue;}const p=pool(sid),ss=sets(sid),seen=new Set();for(let i=0;i<ss.length;i++){const set=ss[i],local=new Set();for(const q of set){const k=fp(q);if(local.has(k))errors.push(`Duplicate inside ${sid} practice ${i+1}`);if(seen.has(k))errors.push(`Overlap between fixed practices for ${sid}`);if(fullFps.has(k))errors.push(`Full-test item reused in fixed practice ${sid}`);local.add(k);seen.add(k);}}if(!p.length)errors.push(`No practice-only questions for ${sid}`);if(s.tested&&p.length<3)warnings.push(`Only ${p.length} distinct practice-only questions for tested skill ${sid}`);skillSummary.push({skill:sid,tested:s.tested,mode:'objective',practiceUnique:p.length,fixedSets:ss.length,fixedSetSizes:ss.map(x=>x.length)});}
if(D.days?.length)errors.push(`Numbered practice sequence still present (${D.days.length} activities)`);
const result={errors,warnings,counts:{skills:Object.keys(D.skills).length,questions:D.questions.length,ecrPrompts:D.ecrPrompts.length,forms:D.forms.length,days:D.days?.length||0,fullObjectiveQuestions:fullIds.size,fullObjectiveFingerprints:fullFps.size},formSummary,skillSummary};
fs.writeFileSync(path.join(dir,'VALIDATION.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(errors.length)process.exit(1);
