const fs=require('fs'),vm=require('vm');const src=fs.readFileSync(__dirname+'/question-bank.js','utf8');const b={window:{}};vm.createContext(b);vm.runInContext(src,b);const D=b.window.StatisticsPracticeData;
function hashString(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}function rng(seed){return mulberry32(hashString(seed));}function shuffle(arr,r){const a=arr.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function alloc(e){if(e.allocation)return e.skills.map(sid=>({sid,count:e.allocation[sid]||0})).filter(x=>x.count>0);const n=e.skills.length,base=Math.floor(e.examCount/n),rem=e.examCount%n;return e.skills.map((sid,i)=>({sid,count:base+(i<rem?1:0)}));}
function balancedDraw(pool,count,seed,blockedIds=new Set()){const candidates=shuffle(pool.filter(q=>!blockedIds.has(q.id)),rng(seed));const groups=[...new Set(candidates.map(q=>q.diagnosticGroup).filter(Boolean))];if(groups.length<2)return candidates.slice(0,count);const selected=[],selectedIds=new Set(),usedVariants=new Set(),groupCounts={};while(selected.length<count){let best=null,bestScore=Infinity;for(let i=0;i<candidates.length;i++){const q=candidates[i];if(selectedIds.has(q.id))continue;const g=q.diagnosticGroup||'general',gc=groupCounts[g]||0,v=q.diagnosticVariant;const variantPenalty=v!==undefined&&usedVariants.has(String(v))?1:0;const score=gc*100+variantPenalty*10+i/candidates.length;if(score<bestScore){best=q;bestScore=score;}}if(!best)break;selected.push(best);selectedIds.add(best.id);groupCounts[best.diagnosticGroup||'general']=(groupCounts[best.diagnosticGroup||'general']||0)+1;if(best.diagnosticVariant!==undefined)usedVariants.add(String(best.diagnosticVariant));}return selected;}
function skillForm(e,sid,count,fi){const used=new Set();let chosen=[];for(let f=0;f<=fi;f++){chosen=balancedDraw(D.questions[sid],count,`${e.id}:${sid}:balanced:${f}`,used);chosen.forEach(q=>used.add(q.id));}return chosen;}
function form(e,fi){let out=[];for(const a of alloc(e))out.push(...skillForm(e,a.sid,a.count,fi));return shuffle(out,rng(`${e.id}:form:${fi}:mix`));}
let errors=[];
for(const [sid,s] of Object.entries(D.skills)){let ids=new Set(),prompts=new Set();for(let v=0;v<3;v++){const qs=D.questions[sid].slice(v*s.quizCount,(v+1)*s.quizCount);if(qs.length!==s.quizCount)errors.push(`${sid} V${v+1} count`);for(const q of qs){if(ids.has(q.id))errors.push(`${sid} repeated id ${q.id}`);ids.add(q.id);if(prompts.has(q.prompt))errors.push(`${sid} repeated exact prompt across fixed versions`);prompts.add(q.prompt);}}}
for(const [eid,e] of Object.entries(D.exams)){let ids=new Set();for(let fi=0;fi<4;fi++){const qs=form(e,fi);if(qs.length!==e.examCount)errors.push(`${eid} form ${fi} count ${qs.length}`);for(const q of qs){if(ids.has(q.id))errors.push(`${eid} repeated question id across fixed forms: ${q.id}`);ids.add(q.id);}for(const a of alloc(e)){const sub=qs.filter(q=>q.skill===a.sid),groups=sub.map(q=>q.diagnosticGroup).filter(Boolean);if(groups.length){const counts={};groups.forEach(g=>counts[g]=(counts[g]||0)+1);const vals=Object.values(counts);if(vals.length>1&&Math.max(...vals)-Math.min(...vals)>1)errors.push(`${eid} form ${fi} unbalanced diagnostic groups for ${a.sid}`);}}}if(e.allocation){const full=Object.entries(e.allocation).filter(([sid])=>sid.endsWith('_full')).reduce((a,[,n])=>a+n,0);if(['e8','e9','e10','e11','e12'].includes(eid)&&full>4)errors.push(`${eid} too many full hypothesis-test questions: ${full}`);}}
const report={errors,exams:Object.keys(D.exams).length,skills:Object.keys(D.skills).length};fs.writeFileSync(__dirname+'/FORMS_VALIDATION.json',JSON.stringify(report,null,2));console.log(`forms validation errors=${errors.length}`);if(errors.length){console.log(errors.slice(0,30));process.exitCode=1;}
